inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - db/schema.rb
    - db/migrate/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - log/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*