development:
  clients:
    default:
      database: yt_betterlist_development
      hosts: [ 'localhost:27017' ]

test:
  clients:
    default:
      database: yt_betterlist_test
      hosts: [ 'localhost:27017' ]